# Generated by Django 5.0.6 on 2025-01-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='date_commission',
            field=models.DateField(blank=True, null=True),
        ),
    ]
